//  Notes
//  If there's an apostrophe in an entry, surround it with double quotes, like this:
//  ["Washing one's face", 'korean'],
//
//  When adding entries, be sure to make each entry end with a comma except for the last one
//
//  To deactivate a single line from the list below, precede it with '//', like this:
//  // ['english', 'korean'],
//
//  To deactivate a section from the list below, delimit it with '/*' and '*/', like this:
//  /*
//  ['english1', 'korean1'],
//  ['english2', 'korean2'],
//  */

const listFromFile = [
  ['Big trouble, serious problem', '큰일'],
  ['Way, method', '방법'],
  ['To be colorful', '화려하다'],
  ['To be better, superior', '낫다'],
  ['To study abroad', '유학 가다'],
  ['Rumor', '소문'],
  ['Magazine' '잡지'],
  ['Red', '빨간색'],
  ['Black', '검은색'],
  ['Dress', '원피스'],
  ['To be close with someone', '친하다'],
  ['Counter for thing, kind, type', '가지'],
  ['Counters for place', '곳 or 군데'],
  ['Method, solution', '방법'],
  ['PhD program', '박사 과정'],
  ['Various', '여러 가지'],
  ['Tuition fees', '등록금'],
  ['To explain', '설명하다'],
  ['Staff', '종업원'],
  ['To be empty, vacant, unoccupied', '비다'],
  ['Customer', '손님'],
  ['To write, put, jot, take down', '적다'],
  ['Vacancy, opening, unoccupied seat', '빈자리'],
  ['To give, offer, more polite than 주다', '드리다'],
  ['To sit', '앉다'],
  ['Window', '창문'],
  ['To close', '닫다'],
  ['To open', '열다'],
  ['To explain', '설명하다'],
  ['Grammar', '문법'],
  ['To be urgent, pressing', '급하다'],
  ['Middle school', '중학교'],
  ['Midterm exam', '중간고사'],
  ['Central', '중앙'],
  ['Related to middle, center, medium', '중'],
  ['To put, lay, place', '놓다'],
  ['To drive', '운전하다'],
  ['Key', '열쇠'],
  ['Wallet', '지갑'],
  ['To find', '찾다'],
  ['Company', '회사'],
  ['Meeting', '회의'],
  ['To turn down', '줄이다'],
  ['I'll see you later', '이따 뵐게요'],
  ['Kindergarten', '유치원'],
  ['Blind person', '장님'],
  ['Visually handicapped person', '시각 장애인'],
  ['Professor', '교수'],
  ['Customer in a business-related context', '고객님'],
  ['Head of company', '사장'],
  ['Section chief', '과장'],
  ['Head of department (manager)', '부장'],
  ['President of a college, dean', '총장'],
  ['Employee', '사원'],
  ['Deputy section chief', '대리'],
  ['Deputy head of department', '차장'],
  ['To take, bring, carry', '가져가다'],
  ['To have', '가지다'],
  ['To stop by, come by, drop by', '들르다'],
  ['To hear from someone', '연락 오다'],
  ['To be too good to throw away', '아깝다'],
  ['Short form of 것이', '게'],
  ['Short form of 이것이', '이게'],
  ['What meaning', '무슨 뜻'],
  ['Department store', '백화점'],
  ['A favor', '부탁'],
  ['A few more days', '며칠 더'],
  ['To return (book, DVD)', '반납하다'],
  ['To be the same, equal to, identical to', '똑같다'],
  ['To do someone a favor', '부탁을 들어주다'],
  ['Speaking of which', '말이 나온 김에'],
  ['Exercise shoes', '운동화'],
  ['Style', '스다일'],
  ['Color', '색깔'],
  ['Very, really', '엄청'],
  ['To be splendid, dazzling, bright', '화려하다'],
  ['To mean, to imply', '의미하다'],
  ['Meaning', '뜻'],
  ['My (honorific)', '제'],
  ['So, you mean... I mean...', '그러니까'],
  ['Already' (something happened sooner than expected, nuance of surprise), '벌써'],
  ['By oneself, alone', '혼자'],
  ['One's whole heart, sincerity', '진심'],
  ['The best', '최고'],
  ['Real, really', '진짜'],
  ['Already (something has happened by the present moment', '이미'],
  ['To go find a place', '찾아 가다'],
  ['After awhile, in a bit', '있다가'],
  ['To be simple', '간단하다'],
  ['To be complicated', '복잡하다'],
  ['By yourself', '혼자서'],
  ['Certainly, surely, definitely, must', '꼭'],
  ['Bicycle','자전거'],
  ['Window', '창문'],
  ['Umbrella', '우산'],
  ['Box', '상자'],
  ['Department store', '백화점'],
  ['Midterm exams', '중간고사'],
  ['Method, solution', '방법'],
  ['Map', '지도'],
  ['Country', '나라'],
  ['Meaning', '뜻'],
  ['End', '끝'],
  ['Walk', '산책'],
  ['Freedom', '자유'],
  ['Friendship', '우정'],
  ['Dream', '꿈'],
  ['World', '세상'],
  ['To pile up', '쌓다'],
  ['To push', '밀다'],
  ['To untie, untangle', '풀다'],
  ['To hug', '안다'],
  ['To drive', '운전하다'],
  ['To part, to break up (with someone)', '헤어지다'],
  ['To use', '사용하다'],
  ['To make a mistake', '실수하다'],
  ['To return (library books, videos)', '반납하다'],
  ['To explain', '설명하다'],
  ['To mean', '의미하다'],
  ['To quit', '그만두다'],
  ['To change', '달라지다'],
  ['To disappear', '없어지다'],
  ['To be convenient', '편리하다'],
  ['To be inconvenient, uncomfortable', '불편하다'],
  ['To be kind', '친절하다'],
  ['To be unkind', '불친절하다'],
  ['To be simple', '간단하다'],
  ['To be complicated', '복잡하다'],
  ['To be tough, challenging', '힘들다'],
  ['To be close to someone', '친하다'],
  ['To be certain', '확실하다'],
  ['To be salty', '짜다'],
  ['Slowly', '천천히'],
  ['Suddenly', '갑자기'],
  ['Just a little while ago, just now', '방금'],
  ['Continuously', '계속'],
  ['Occasionally', '때때로'],
  ['Soon after', '금방']  
  ]
