//  Notes
//  If there's an apostrophe in an entry, surround it with double quotes, like this:
//  ["Washing one's face", 'korean'],
//
//  When adding entries, be sure to make each entry end with a comma except for the last one
//
//  To deactivate a single line from the list below, precede it with '//', like this:
//  // ['english', 'korean'],
//
//  To deactivate a section from the list below, delimit it with '/*' and '*/', like this:
//  /*
//  ['english1', 'korean1'],
//  ['english2', 'korean2'],
//  */

const listFromFile = [
  ['Company', '회사'],
  ['Library', '도서관'],
  ['Bookstore', '서점'],
  ['To ask', '묻다'],
  ['To come in', '들어오다'],
  ['To collect, to gather', '모으다'],
  ['To pick up, to hold', '들다'],
  ['To cut', '자르다'],
  ['To be beautiful', '어름답다'],
  ['To be cold (temperature/to touch)', '차갑다'],
  ['To be cheap', '싸다'],
  ['To be okay', '괜찮다'],
  ['To be easy', '쉽다'],
  ['To be wide', '넓다'],
  ['To be different', '다르다'],
  ['To be similar', '비슷하다'],
  ['Maybe, probably', '아마 / 아마도'],
  ['For a long time', '오래'],
  ['In front of', '앞에'],
  ['Behind', '뒤에'],
  ['Next to, beside', '옆에'],
  ['On top of, over', '위에'],
  ['Under, below', '밑에'],
  ['Related to learning, studying, school', '학'],
  ['Student', '학생'],
  ['School', '학교'],
  ['Private academy', '학원'],
  ['Mathematics', '수학'],
  ['Science', '과학'],
  ['Language learning', '어학'],
  ['Linguistics', '언어학'],
  ['Economics', '경제학'],
  ['Scholar', '학자'],
  ['Study abroad', '유학'],
  ['Student studying abroad', '유학생'],
  ['To change schools', '전학'],
  ['Student who changed schools', '전학생'],
  ['School year', '학년'],
  ['Semester', '학기'],
  ['School vacation', '방학'],
  ['Scholarship', '장학금'],
  ['Student on a scholarship', '장학생'],
  ['Student who as returned to school (usually) after a long break', '복학생'],
  ['(Formal) learning, studies', '학습'],
  ['Self-study, studying by oneself', '독학'],
  ['Related to room', '실'],
  ['Toilet, bathroom', '화장실'],
  ['Dressing room, backstage powder room (theater/stage)', '분장실'],
  ['Classroom', '교실'],
  ['Practice room', '연습실'],
  ['Waiting room', '대기실'],
  ['Meeting/conference room', '회의실'],
  ['Hospital room', '병실'],
  ['Beauty parlor/hair salon', '미용실'],
  ['Office', '사무실'],
  ["Teacher's office", '교무실'],
  ['Head of the office', '실장'],
  ['Indoors', '실내'],
  ['Outdoors, outside', '실외']
]
