//  Notes
//  If there's an apostrophe in an entry, surround it with double quotes, like this:
//  ["Washing one's face", 'korean'],
//
//  When adding entries, be sure to make each entry end with a comma except for the last one
//
//  To deactivate a single line from the list below, precede it with '//', like this:
//  // ['english', 'korean'],
//
//  To deactivate a section from the list below, delimit it with '/*' and '*/', like this:
//  /*
//  ['english1', 'korean1'],
//  ['english2', 'korean2'],
//  */

const listFromFile = [
  ['Any', '아무'],
  ['Anyone, anybody', '아무나'],
  ['Anything', '아무거나'],
  ['Anywhere, any place', '아무 데나'],
  ['Nobody, not anybody', '아무도'],
  ['Nothing, not anything', '아무것도'],
  ['Nowhere, not any place', '아무 데도'],
  ['Anytime, just anytime', '아무 때나'],
  ['No word, no mention', '아무 말도 / 아무 이야기도'],
  ['To be all right, okay, unaffected by', '아무렇지도 않다'],
  ['To nobody', '아무한테도'],
  ['However you like it, just in any way', '아무렇게나'], 
  ['There is no (noun) of any kind', '아무(런) + noun + 도 + 없어요'],
  ['It\'s nothing', '아무것도 아니에요'],
  ['(Relates to) movement, move, to move', '동'], 
  ['Exercise, workout', '운동'],
  ['Movement, move', '동작'],
  ['Operation (of a device)', '작동'],
  ['Activity', '활동'],
  ['Verb', '동사'],
  ['Animal', '동물'],
  ['Linkage, interlocking (internet term)', '연동'],
  ['Behavior', '행동'],
  ['Video', '동영상'],
  ['Among, between (choosing from a few options)', '중에사'],
  ['Among, between (relationships)', '사이에사'], 
  ['Between (physical space)', '사이에'],
  ['(Related to) not', '부/불 (부 when followed by ㅈ or ㄷ)'],
  ['Anxiety, anxious', '불안'], 
  ['Comfortable, relaxed', '안'],
  ['Inconvenient, uncomfortable', '불편'],
  ['Comfortable, convenient', '편'],
  ['Incomplete', '불완전'],
  ['Complete', '완전'],
  ['Imbalance', '불균형'],
  ['Balance', '균형'],
  ['Complaint', '불만'],
  ['Full', '만'],
  ['Incorrect, inaccurate', '부정확'],
  ['Correct', '정확'],
  ['Carelessness', '부주의'],
  ['Attention', '주의'],
  ['Wrong, unfair, unjust', '부당' ],
  ['Correct, right', '당'],
  ['Inappropriate', '부적절'],
  ['Proper', '적절'],
  ['Sometimes', '가끔'],
  ['Often', '자주'],
  ['Always', '항상'],
  ['Always, all the time', '맨날'],
  ['Seldom, rarely', '별로'],
  ['Not at all', '전혀'],
  ['Almost (but) not all', '거의'],
  ['To push', '밀다'],
  ['You (반말)', '너 (네가 written / 니가 spoken'],
  ['Cough', '기침'],
  ['To be heavy, severe, violent, harsh', '심하다'],
  ['To catch, be caught', '걸리다'],
  ['To touch', '만지다'],
  ['To throw', '던지다'],
  ['To recommend', '추천하다'],
  ['Certainly, surely, undoubtedly, exactly', '꼭'],
  ['To ask', '물어보다'],
  ['To look into something, to recognize', '알아보다'],
  ['To keep a watchful eye on someone/something', '지켜보다'],
  ['At once, immediately, straight, instantly, right away, right now', '바로'],
  ['To walk', '걷다'],
  ['Most/best (adverb)', '제일'],
  ['Most/best (adverb)', '가장'],
  ['To wear', '신다'],
  ['Less/not completely (adverb)', '덜'],
  ['Novel', '소설']
  ]
