//  Notes
//  If there's an apostrophe in an entry, surround it with double quotes, like this:
//  ["Washing one's face", 'korean'],
//
//  When adding entries, be sure to make each entry end with a comma except for the last one
//
//  To deactivate a single line from the list below, precede it with '//', like this:
//  // ['english', 'korean'],
//
//  To deactivate a section from the list below, delimit it with '/*' and '*/', like this:
//  /*
//  ['english1', 'korean1'],
//  ['english2', 'korean2'],
//  */

const listFromFile = [
  ['To get into an accident', '사고가 나다'],
  ['To get caught', '들키다 / 잡히다'],
  ['To miss the train', '기차를 놓치다'],
  ['To fall off a chair', '의자에서 떨어지다'],
  ['To get hit by a car', '차에 치이다'],
  ['To say/tell/speak/talk', '말하다'],
  ['To die', '죽다'],
  ['To cry', '울다'],
  ['Trouble, effort, hard work', '수고'],
  ['Keep up the good work', '수고하세요'],
  ['You worked hard', '수고하셨습니다'],
  ['Your effort has been a lot', '수고 많으셨습니다'],
  ['To be smart, clever', '똑똑하다'],
  ['To do something well, to be good at something, to do something often, to be kind to someone', '잘하다'],
  ['To be curious', '궁금하다'],
  ['To be awkward', '어색하다'],
  ['To look forward to, to anticipate, to expect', '기대하다'], 
  ['To be hard, to be difficult, to be tough', '힘들다'],
  ['Younger sister', '여동생'],
  ['Doorbell', '초인종'],
  ['To press, to push', '누르다'],
  ['Answer, reply', '답'],
  ['To fall asleep', '잠들다'], 
  ['To like / to enter one\'s heart', '마음에 들다'],
  ['Alone, by oneself', '혼자'],
  ['To depart, to leave', '출발하다'],
  ['To play soccer', '축구를 하다'],
  ['Zoo', '동물원'],
  ['Ball', '공'],
  ['To be cancelled', '취소되다'],
  ['Backpacking trip', '배낭여행'],
  ['Refrigerator', '냉장고'],
  ['Player', '선수'],
  ['Customer', '손님'],
  ['Continuously', '계속'],
  ['Recently', '최근에'],
  ['To mull over, to contemplate', '고민하다'],
  ['To call, to invite', '부르다'],
  ['To solve', '풀다'],
  ['To pass by', '지나가다'],
  ['To work part-time', '아르바이트하다'],
  ['To quit', '그만두다'],
  ['Anything, doesn\'t matter what', '아무거나'],
  ['Anywhere, any place', '아무 데나'],
  ['First place winner', '일 등'],
  ['Theme park', '놀이공원'],
  ['Criminal, culprit', '범인'],
  ['To fall in love', '반하다'],
  ['To recommend', '추천하다'],
  ['To run', '달려가다'],
  ['To drop something', '떨어뜨리다'],
  ['To breakdown, to stop working', '고장 나다'],
  ['News', '소식'],
  ['Actor/Actress', '배우'],
  ['To try and listen, to have heard', '들어 보다'],
  ['Many, a lot of', '여러 가지'],
  ['Meaning', '뜻'],
  ['To come and hang out', '놀러 오다'],
  ['Website', '웹사이트'], 
  ['Related to writing or letter', '문'],
  ['Culture', '문화'],
  ['Document, papers', '문서'],
  ['Sentence', '문장'],
  ['Letter, character', '문자'],
  ['Literature', '문학'],
  ['Grammar', '문법'],
  ['Order', '주문'],
  ['Thesis, research paper', '논문'],
  ['Cultural assets, cultural properties', '문화재'],
  ['Related to gathering or gather', '화'],
  ['Company', '회사'],
  ['Employee/worker', '회사원'],
  ['School employee', '교직원'],
  ['Meeting', '회의'],
  ['Meeting/conference room #1', '회의실'],
  ['Big/main conference room', '대회의실'],
  ['Meeting/conference room #2', '회의장'],
  ['Company dinner', '회식'],
  ['Accounting', '회계'],
  ['Calculator', '계산기'],
  ['Counter', '계산대'],
  ['Calculation', '계산'],
  ['Accountant', '회계사'],
  ['Accounting department', '회계 부서'],
  ['Membership fee/dues', '회비'],
  ['Expense, cost', '비용'],
  ['Member/membership', '회원'],
  ['Foreign language conversation', '회화'],
  ['Society', '사회'],
  ['National Assembly', '국회'],
  ['Competition, tournament', '대회'],
  ['College, university', '대학교'],
  ['(Large) public park', '대공원'],
  ['Church', '교회'],
  ['Religion', '종교'],
  ['Buddhist temple', '절'],
  ['Catholic church/cathedral', '성당'],
  ['Club, society', '동호회'],
  ['To suit', '어울리다'],
  ['To be thick, heavy', '진하다'],
  ['To need', '필요하다'],
  ['To be boring', '지루하다'],
  ['Town, neighborhood', '동네'],
  ['To clean (up)', '청소하다'],
  ['Move', '이사'],
  ['Makeup', '화장'],
  ['By any chance', '혹시'],
  ['Any, what, which, what kind of', '어떤'], 
  ['To bake', '굽다'],
  ['To pass by', '지나가다'], 
  ['In a flash, dramatically', '확'],
