//  Notes
//  If there's an apostrophe in an entry, surround it with double quotes, like this:
//  ["Washing one's face", 'korean'],
//
//  When adding entries, be sure to make each entry end with a comma except for the last one
//
//  To deactivate a single line from the list below, precede it with '//', like this:
//  // ['english', 'korean'],
//
//  To deactivate a section from the list below, delimit it with '/*' and '*/', like this:
//  /*
//  ['english1', 'korean1'],
//  ['english2', 'korean2'],
//  */

const listFromFile = [
  ['Big trouble, serious problem', '큰일'],
  ['Way, method', '방법'],
  ['To be colorful', '화려하다'],
  ['To be better, superior', '낫다'],
  ['To study abroad', '유학 가다'],
  ['Rumor', '소문'],
  ['Magazine' '잡지'],
  ['Red', '빨간색'],
  ['Black', '검은색'],
  ['Dress', '원피스'],
  ['To be close with someone', '친하다'],
  ['Counter for thing, kind, type', '가지'],
  ['Counters for place', '곳 or 군데'],
  ['Method, solution', '방법'],
  ['PhD program', '박사 과정'],
  ['Various', '여러 가지'],
  ['Tuition fees', '등록금'],
  ['To explain', '설명하다'],
  ['Staff', '종업원'],
  ['To be empty, vacant, unoccupied', '비다'],
  ['Customer', '손님'],
  ['To write, put, jot, take down', '적다'],
  ['Vacancy, opening, unoccupied seat', '빈자리'],
  ['To give, offer, more polite than 주다', '드리다'],
  ['To sit', '앉다'],
  ['Window', '창문'],
  ['To close', '닫다'],
  ['To open', '열다'],
  ['To explain', '설명하다'],
  ['Grammar', '문법'],
  ['To be urgent, pressing', '급하다'],
  ['Middle school', '중학교'],
  ['Midterm exam', '중간고사'],
  ['Central', '중앙'],
  ['Related to middle, center, medium', '중'],
  ['To put, lay, place', '놓다'],
  ['To drive', '운전하다'],
  ['Key', '열쇠'],
  ['Wallet', '지갑'],
  ['To find', '찾다'],
  ['Company', '회사'],
  ['Meeting', '회의'],
  ['To turn down', '줄이다'],
  ['I'll see you later', '이따 뵐게요'],
  ['Kindergarten', '유치원'],
  ['Blind person', '장님'],
  ['Visually handicapped person', '시각 장애인'],
  ['Professor', '교수'],
  ['Customer in a business-related context', '고객님'],
  ['Head of company', '사장'],
  ['Section chief', '과장'],
  ['Head of department (manager)', '부장'],
  ['President of a college, dean', '총장'],
  ['Employee', '사원'],
  ['Deputy section chief', '대리'],
  ['Deputy head of department', '차장'],
  ['To take, bring, carry', '가져가다'],
  ['To have', '가지다'],
  ['To stop by, come by, drop by', '들르다'],
  ['To hear from someone', '연락 오다'],
  ['To be too good to throw away', '아깝다'],
  ['Short form of 것이', '게'],
  ['Short form of 이것이', '이게'],
  ['What meaning', '무슨 뜻'],
  ['Department store', '백화점'],
  ['A favor', '부탁'],
  ['A few more days', '며칠 더'],
  ['To return (book, DVD)', '반납하다']
  ]
